name: 'Install dependencies'
description: 'Install all required dependencies'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: python3 -m pip install -r requirements.txt

    - uses: actions/cache@v3
      with:
        # with this we are going to cache the virtual environment
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}